name: Deploy to production

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'web1-tm-with-friends'
        image: 'docker.io/garridoy/tm-with-friends:latest'
        region: 'europe-west1'
        env_vars: |-
          CLIENT_ID=${{ secrets.CLIENT_ID }}
          CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          ENCODED_CREDENTIALS=${{ secrets.ENCODED_CREDENTIALS }}

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
